---
- name: disable default in sites-enabled
  file:
   path: /etc/nginx/sites-enabled/default
   state: absent
   
- name: create a virtualhost
  template:
   src: templates/nginx_virtualhost.conf.j2
   dest: '/etc/nginx/sites-available/{{ server_name.0 }}.conf'
 
- name: enable our site
  file:
   src: '/etc/nginx/sites-available/{{ server_name.0 }}.conf'
   dest: '/etc/nginx/sites-enabled/{{ server_name.0 }}.conf'
   state: link
  notify:
   - restart-nginx
