---
- set_fact:
   server_name: "{{ outer_item.domaine.split('.') }}"

- include: ./create_l.yml

- include: './{{ webServer }}/{{ ansible_os_family }}_configure_port.yml'  
  when:  webServer == "apache"
 
- include: './{{ webServer }}/{{ ansible_os_family}}_virtualhost_conf.yml'

